### PR TITLE
Rate limit

### PR DESCRIPTION
**Pull request by jchris**
I'm not happy with this yet, because it only catches errors and not places where the UI is querying a success response in a tight loop as fast as it can.

Because the NavTree can fire many queries to load schema, putting the rate limiter across all requests requires a higher threshold.

This isn't ready to merge yet but I'm ready for feedback, maybe there's a better way to do it.

The user experience goal I'm trying to hit, is: "the FaunaDB dashboard should never be the reason your laptop fan spins up"

### CODE REVIEW

**Comment by jchris** [comment]
related issue https://github.com/faunadb/dashboard/issues/84

**Comment by erickpintor** [comment]
I'm ok with adding a rate limit for now but, I think this is a symptom of a deeper architecture problem: we're relying too much on react to manage our global state, which is really fragile.

Refer to:  https://faunadb.atlassian.net/wiki/display/SE/Schema+Tree+Hierarchy

**Comment by erickpintor** [comment]
Shouldn't we merge this rate limit, just for safety?

**Comment by jchris** [comment]
Let me review it again.

**Comment by jchris** [comment]
rebased to master, don't want to merge until I have a bug that is making infinite-requests, that I can use to repro against.

**Pull request closed without merging**
