### PR TITLE
Header link to dashboard tour

### PR DESCRIPTION
**Pull request by jchris**
This just adds a link to the mock up of the dashboard tour so we have something anything for users. In time we can make this link actually start the tour for people who want to run it twice.

### CODE REVIEW

**Comment by jchris** [comment]
this PR has an extra commit, I'll rebase it against master. Right now I'm focusing on production, which just has two commits since we moved to focus on the new-dash code.

**Comment by jchris** [comment]
This is in production now but we should review the patch to master normally.

**Comment by erickpintor** [comment]
This link was not in production when I checked so, I'm leaving it out of the next deploy.
Do we still want this link at the header?

**Comment by jchris** [comment]
lets not merge this. the content is mostly duplicated by the new inline quickstart

**Pull request closed without merging**
