### PR TITLE
Create a data model for our dashboard

### PR DESCRIPTION
**Pull request by marrony**

### CODE REVIEW

**Comment by erickpintor** [comment]
Would you mind sharing your thoughts about the data model? What are the advantages? How do you imagine this evolving along the project's development?

I can see some advantages in the code but, as off now, they are mostly indirections in between the reducers and the data being transformed. The classes don't incapsulate behavior rather than create copies of themselves.

I think this is an important discussion to have. Have you consider typescript interfaces?

**Comment by marrony** [comment]
My idea with this was to make it clear and easy to see the shape of data as js don't help us in this task. And using classes instead of plain objects make it easy for us to debug since you can see the "type" in the browser. Also, this is a step forward if we want to adopt typescript

> The classes don't incapsulate behavior rather than create copies of themselves.

Isn't that the idea of redux?

> Have you consider typescript interfaces?

I don't understand this question, we don't have any support to typescript yet.

**Comment by jchris** [comment]
My concern with encapsulating state objects with classes is, does it preclude us from making the application's state into one giant ImmutableJS object? If we do that, we can subscribe to state events from the object, etc.

**Comment by erickpintor** [comment]
I think I like redux because its approach for state management is simple. Adding classes seems to also add lot more boilerplate because ES6 has more operators to deal with plain objects that it has to deal with immutable classes. 

Debugging is a nice but not very strong feature in favor of class oriented development since the atual types don't matter, only the data matters.

If we think about it as a step towards TypeScript, it also doesn't really apply because TypeScript's interfaces would be a better fit, in my opinion of course. Interfaces can enforce strong typed data structures but also allowing us to take advantage of plain object utilities.

I think I personally prefer to keep global state as a immutable object and use types to differ data structures at a small granularity. Like recognizing different types of users, for example.

I like @jchris vision of a immutable object where you can subscribe to changes at a certain path. Although, it seems a little redundant after the adoption of redux.

**Comment by jchris** [comment]
I think there would still be work for redux to do, with an immutable core. Basically it would be in charge of converting state format to props format that different components expect, and converting changes to the canonical state format.

Thanks for articulating the thing about plain objects. It's always been how I've felt but with my Erlang background I figured it was because my mind was polluted. :) 

Which leads to [my favorite Joe Armstrong quote.](http://www.johndcook.com/blog/2011/07/19/you-wanted-banana/)

**Pull request closed without merging**
