### PR TITLE
Add note about keys containment

### PR DESCRIPTION
**Pull request by erickpintor**
Fixes: #201 

image

### CODE REVIEW

**Comment by erickpintor** [comment]
@jchris is that message good enough? I'm not sure if it fits in the way you're explaining containers to people.

**Comment by jchris** [comment]
I think it is good enough? but what if we change the model, so that we displayed a databases keys inside it instead of the parent. I realize the underlying data model won't change but then we won't have to explain it to users...

**Comment by jchris** [comment]
LGTM we should merge the note and then consider if we want a bigger change.

**Comment by freels** [comment]
> but what if we change the model, so that we displayed a databases keys inside it instead of the parent.

I just want to chime in to say that this is the long-term plan for the db proper.

**Pull request merged**
