### PR TITLE
Display instances data as a table like view for class indexes

### PR DESCRIPTION
**Pull request by erickpintor**
image

### CODE REVIEW

**Comment by erickpintor** [comment]
@jchris I think that's what we were talking about during last meeting.

**Comment by jchris** [comment]
that is the right display, but it should be under the class view, not the indexes view. And automatically run the query on a covering index with no terms if it exits

**Comment by jchris** [comment]
I'm not sure if it is more or less confusing to bring up the associated instances in the index table. maybe more confusing ...

**Comment by erickpintor** [comment]
That will require a little bit of more work. Let me think about this and open another PR later.

**Pull request closed without merging**
